sonar.projectKey=blog
sonar.projectName=Anshuman Biswas Blog
sonar.sources=.
sonar.tests=tests/go
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/node_modules/**,**/vendor/**,**/tmp/**,**/migrations/**,**/static/**,**/templates/**,**/pids/**,**/logs/**,**/*.gohtml
sonar.scanner.socketTimeout=120
sonar.scanner.connectTimeout=30
